### ISSUE TITLE
点第二首歌的时候切歌页面会消失

### ISSUE THREAD

**Issue by OneTrueSum95** [RealSeek/KookOrderSongPlugin#3]
后台报错 
```
[11:33:03] [Event Executor/WARN]: Unexpected old message from remote. Dropped it.
[11:33:03] [Event Executor/WARN]: Unexpected old message from remote. Dropped it.
[11:33:04] [Event Executor/INFO]: [KookOrderSong] Dream On 已添加，当前歌曲: Dream On - Aerosmith 歌单内歌曲数量:3
>
[11:35:03] [Event Executor/ERROR]: Unexpected exception while we attempting to execute command from remote.
 snw.jkook.command.CommandException: Something unexpected happened.
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommandNow(CloudBasedCommandManager.java:172) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudCommandManagerImpl.executeCommand(CloudCommandManagerImpl.java:59) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.network.ListenerImpl.executeCommand(ListenerImpl.java:222) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.network.ListenerImpl.event0(ListenerImpl.java:154) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.network.ListenerImpl.event(ListenerImpl.java:108) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.network.ListenerImpl.lambda$handle$0(ListenerImpl.java:69) ~[kookbc-0.27.2.jar:0.27.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_371]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_371]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_371]
Caused by: cloud.commandframework.exceptions.CommandExecutionException: java.lang.RuntimeException: Unexpected IOException when we attempting to call request.
        at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:129) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:316) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:254) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommandNow(CloudBasedCommandManager.java:167) ~[kookbc-0.27.2.jar:0.27.2]
        ... 8 more
Caused by: java.lang.RuntimeException: Unexpected IOException when we attempting to call request.
        at snw.kookbc.impl.network.NetworkClient.call(NetworkClient.java:101) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.HttpAPIImpl.uploadFile(HttpAPIImpl.java:134) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.HttpAPIImpl.uploadFile(HttpAPIImpl.java:156) ~[kookbc-0.27.2.jar:0.27.2]
        at me.realseek.kookordersongplugin.message.Card.playCard(Card.java:106) ~[?:?]
        at me.realseek.kookordersongplugin.util.OrderVoid.order(OrderVoid.java:93) ~[?:?]
        at me.realseek.kookordersongplugin.command.netease.NeteaseAudio.onCommand(NeteaseAudio.java:22) ~[?:?]
        at snw.kookbc.impl.command.cloud.CloudWrappedCommandExecutionHandler.execute(CloudWrappedCommandExecutionHandler.java:82) ~[kookbc-0.27.2.jar:0.27.2]
        at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[kookbc-0.27.2.jar:0.27.2]
        at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:316) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:254) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommandNow(CloudBasedCommandManager.java:167) ~[kookbc-0.27.2.jar:0.27.2]
        ... 8 more
Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.kt:567) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.kt:532) ~[kookbc-0.27.2.jar:0.27.2]
        at okio.ForwardingSink.write(ForwardingSink.kt:29) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218) ~[kookbc-0.27.2.jar:0.27.2]
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255) ~[kookbc-0.27.2.jar:0.27.2]
        at okio.RealBufferedSink.write(RealBufferedSink.kt:185) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.RequestBody$Companion$toRequestBody$2.writeTo(RequestBody.kt:152) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[kookbc-0.27.2.jar:0.27.2]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.network.NetworkClient.call(NetworkClient.java:87) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.HttpAPIImpl.uploadFile(HttpAPIImpl.java:134) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.HttpAPIImpl.uploadFile(HttpAPIImpl.java:156) ~[kookbc-0.27.2.jar:0.27.2]
        at me.realseek.kookordersongplugin.message.Card.playCard(Card.java:106) ~[?:?]
        at me.realseek.kookordersongplugin.util.OrderVoid.order(OrderVoid.java:93) ~[?:?]
        at me.realseek.kookordersongplugin.command.netease.NeteaseAudio.onCommand(NeteaseAudio.java:22) ~[?:?]
        at snw.kookbc.impl.command.cloud.CloudWrappedCommandExecutionHandler.execute(CloudWrappedCommandExecutionHandler.java:82) ~[kookbc-0.27.2.jar:0.27.2]
        at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[kookbc-0.27.2.jar:0.27.2]
        at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:316) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommand(CloudBasedCommandManager.java:254) ~[kookbc-0.27.2.jar:0.27.2]
        at snw.kookbc.impl.command.cloud.CloudBasedCommandManager.executeCommandNow(CloudBasedCommandManager.java:167) ~[kookbc-0.27.2.jar:0.27.2]
        ... 8 more
[11:35:09] [Thread-2/INFO]: [KookOrderSong] Dream On - Aerosmith 已播放完毕
[11:35:21] [Event Executor/WARN]: Unexpected old message from remote. Dropped it.
[11:35:21] [Event Executor/WARN]: Unexpected old message from remote. Dropped it.
[11:35:21] [Thread-2/INFO]: [KookOrderSong] 列表内还有歌曲，继续播放
[11:35:21] [pool-4-thread-2/INFO]: [KookOrderSong] 当前播放: 望春风 - 陶喆
[11:35:22] [Event Executor/INFO]: [KookOrderSong] I Want You 已添加，当前歌曲: 望春风 - 陶喆 歌单内歌曲数量:3
>
[11:37:36] [Thread-2/ERROR]: Exception in thread "Thread-2" java.lang.RuntimeException: Unexpected IOException when we attempting to call request.
[11:37:36] [Thread-2/ERROR]:    at snw.kookbc.impl.network.NetworkClient.call(NetworkClient.java:101)
[11:37:36] [Thread-2/ERROR]:    at snw.kookbc.impl.HttpAPIImpl.uploadFile(HttpAPIImpl.java:134)
[11:37:36] [Thread-2/ERROR]:    at snw.kookbc.impl.HttpAPIImpl.uploadFile(HttpAPIImpl.java:156)
[11:37:36] [Thread-2/ERROR]:    at me.realseek.kookordersongplugin.message.Card.playCard(Card.java:54)
[11:37:36] [Thread-2/ERROR]:    at me.realseek.kookordersongplugin.playmusic.PlayMusic.playMusic(PlayMusic.java:82)
[11:37:36] [Thread-2/ERROR]:    at me.realseek.kookordersongplugin.playmusic.PlayMusic.run(PlayMusic.java:130)
[11:37:36] [Thread-2/ERROR]:    at java.lang.Thread.run(Unknown Source)
[11:37:36] [Thread-2/ERROR]: Caused by: java.net.SocketTimeoutException: timeout
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.kt:567)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.kt:532)
[11:37:36] [Thread-2/ERROR]:    at okio.ForwardingSink.write(ForwardingSink.kt:29)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
[11:37:36] [Thread-2/ERROR]:    at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
[11:37:36] [Thread-2/ERROR]:    at okio.RealBufferedSink.write(RealBufferedSink.kt:185)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.RequestBody$Companion$toRequestBody$2.writeTo(RequestBody.kt:152)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[11:37:36] [Thread-2/ERROR]:    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
[11:37:36] [Thread-2/ERROR]:    at snw.kookbc.impl.network.NetworkClient.call(NetworkClient.java:87)
[11:37:36] [Thread-2/ERROR]:    ... 6 more
>
```

**Comment by RealSeek** [comment]
配置有误，已帮他解决
